language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev -v

script:
  - pytest

notifications:
  email:
    recipients:
      - jragonmiris@gmail.com
    on_success: change
    on_failure: always
